### ISSUE TITLE
troubleshot

### ISSUE THREAD

**Issue by amiscau** [dewanakl/undangan#1]
hallo kak, ini kenapa ya tidak jalan 🙏🏻
terima kasih. 

![5AFD2728-BCFB-416C-8307-87949724B25B](https://user-images.githubusercontent.com/130718313/231917933-e027ba45-dbf5-415f-8f17-e355d776c68d.jpeg)

**Comment by amiscau** [comment]
> ![image](https://user-images.githubusercontent.com/53048107/231919834-928288f9-9d0c-467e-9493-2c2171001e83.png)
> 
> dibagian data-waktu coba di cek lagi kak

sebenarnya sudah jalan kak, (di window + android) tidak ada kendala, namun di iOS tampilannya spt itu, 🙏🏻

**Comment by dewanakl** [comment]
coba lagi ini kak, sudah saya update di bagian app.js

**Comment by amiscau** [comment]
> coba lagi ini kak, sudah saya update di bagian app.js

masih sama kak, tidak muncul timer nya. 
termasuk juga sound nya, tidak auto play padahal kalo di window auto.

**Comment by dewanakl** [comment]
https://dewanakl.github.io/undangan/

kalau coba link demo ini bisa nggak kak?

**Comment by amiscau** [comment]
> https://dewanakl.github.io/undangan/
> 
> kalau coba link demo ini bisa nggak kak?

![DA9DF077-65AD-4C51-98CC-65785BB749B7](https://user-images.githubusercontent.com/130718313/231951088-19e9b34f-3c80-4524-9dc2-1254129aea7c.png)

sound tidak auto play + timer nya spt itu kak

**Comment by amiscau** [comment]
> > https://dewanakl.github.io/undangan/
> > kalau coba link demo ini bisa nggak kak?
> 
> ![DA9DF077-65AD-4C51-98CC-65785BB749B7](https://user-images.githubusercontent.com/130718313/231951088-19e9b34f-3c80-4524-9dc2-1254129aea7c.png)
> 
> sound tidak auto play + timer nya spt itu kak

**Comment by dewanakl** [comment]
Sebentar kak, saya coba lagi

**Comment by amiscau** [comment]
> Sebentar kak, saya coba lagi

saya coba pakai browser chrome, mozilla, safari, google sama aja kak, apa mungkin iOS nya yang bermasalah ya

**Comment by dewanakl** [comment]
Ada temen yang pake ios lain juga kak? untuk uji coba

**Comment by dewanakl** [comment]
Pastikan javascript sudah aktif ya kak

**Comment by amiscau** [comment]
> Ada temen yang pake ios lain juga kak? untuk uji coba


di iOS temen sya juga spt ini kak. 
javascript sudah aktif masih sama aja

**Comment by dewanakl** [comment]
Kalau data komentarnya muncul nggak kak ?

**Comment by amiscau** [comment]
muncul kak, selain itu semuanya normal

**Comment by dewanakl** [comment]
wahh siap kak

**Comment by amiscau** [comment]
> Coba test lagi kak

masih tetap sama kak 🙏🏻

**Comment by amiscau** [comment]
> Kalau masnya ada mac bisa inspect element lalu ss mas


aduh gada kak 🥲
saya coba hubungi minta bantuan temen dulu ya.

**Comment by dewanakl** [comment]
![65990f90-9591-4f58-8486-2fc5875942dd](https://user-images.githubusercontent.com/53048107/232194311-a1891c14-0606-4d34-b381-10ea060ca9dd.jpg)

Saya tanya teman saya bisa mas

**Comment by amiscau** [comment]
> ![65990f90-9591-4f58-8486-2fc5875942dd](https://user-images.githubusercontent.com/53048107/232194311-a1891c14-0606-4d34-b381-10ea060ca9dd.jpg)
> 
> Saya tanya teman saya bisa mas

sound nya autoplay tidak kak?

**Comment by dewanakl** [comment]
Bisa kak, coba kak buka lewat mac lalu inspect element apakah ada error?

**Comment by dewanakl** [comment]
https://dewanakl.github.io/undangan/?to=Teman+teman+semua

coba test lagi ini kaa

**Comment by dewanakl** [comment]
https://dewanakl.github.io/undangan/?to=Teman+teman+semua

**Comment by dewanakl** [comment]
coba lagi kak, untuk nama (Teman teman semua) muncul tidak kak? sewaktu baru dibuka?

**Comment by amiscau** [comment]
mantap kak, problem solved. 
- nama muncul 
- timer 
- autoplay sound

**Comment by dewanakl** [comment]
Sudah solved semua berarti ya kak?

- [ ] nama sudah muncul
- [ ] count down waktu acara
- [ ] autoplay backsound

**Comment by amiscau** [comment]
> Sudah solved semua berarti ya kak?
> 
> * [x]  nama sudah muncul
> * [x]  count down waktu acara
> * [x]  autoplay backsound

di bagian design logo bank kak, jadi bulet 🙏🏻

**Comment by dewanakl** [comment]
oh iya kak, ikut ke ganti jadinya

**Comment by dewanakl** [comment]
coba cek lagi kak, apakah sudah sesuai semuanya?

**Comment by dewanakl** [comment]
saya close ya kak, thank you

**Comment by dewanakl** [comment]
Permisi kak, crosscheck xss security pada kolom kometar apakah bisa melihat text "<script>alert('hack')</script>" pada awal awal komentar?
