### ISSUE TITLE
rev

### ISSUE THREAD

**Issue by amiscau** [dewanakl/undangan#2]
mohon maaf, dibuat seperti ini barangkali bisa enggak mas @dewanakl  🙏🏻 
terima kasih. 

![AA8C78E7-F8FB-4A85-8AD3-9278FBA0FA72](https://user-images.githubusercontent.com/130718313/234434310-41c6553d-039e-4cda-88b7-13084d9f8bdd.jpeg)

![298B511D-B01F-4ADD-B194-6DDFA8708B50](https://user-images.githubusercontent.com/130718313/234435433-a33f1b74-d915-4770-a4a0-d229e132d88c.jpeg)

#sorting
#show
#tabel

**Comment by amiscau** [comment]
di bagian ucapan ini puanjang dan sangat banyak. 

https://dewanakl.github.io/undangan/?to=Teman+teman+semua#ucapan

**Comment by dewanakl** [comment]
bisa kak, terima kasih masukannya kak

**Comment by dewanakl** [comment]
Sudah kak, mohon tanggapannya kembali

**Comment by amiscau** [comment]
mantap kak, perfect poll 👍🏻 🤩

**Comment by dewanakl** [comment]
Oke kak, saya close ya
