### ISSUE TITLE
Key error message

### ISSUE THREAD

**Issue by thnguyen996** [dewanakl/undangan#23]
Hello, great work on the website!!! 

I am trying to use your template and there is an error while connecting the backend api with the frontend. 
This is the error: 
<img width="827" alt="image" src="https://github.com/dewanakl/undangan/assets/68097476/74d1940c-fa3d-4f09-958d-42d1ea6a9507">

I'm using database service from render.com and backend server is deployed on vercel. 

Here is the body part of the index.html file: 
`<body data-key="(APP_KEY from .env of backend)" data-url="https://wedding-site-backend.vercel.app/" style="overflow-y: hidden;">
`

**Comment by dewanakl** [comment]
Hello..

Step for get key:
1. Go to dashboard.html
2. email and password is user@example.com and 1-8
3. Setting
4. and copy key
5. paste in index.html

Ensure test with postman for backend api work no error
Thank you

**Comment by thnguyen996** [comment]
Hello, 

Thank you for answering so quickly. 
I typed in the email and pw but I got unauthorized message: 
 
<img width="1212" alt="image" src="https://github.com/dewanakl/undangan/assets/68097476/a6ba2bcc-3e1b-4849-9bca-87b4ea78b67b">

**Comment by dewanakl** [comment]
Ensure check in dashboard.html
data-url is the same in index.html

Thank you

**Comment by thnguyen996** [comment]
It worked. Thank you so much!!!
