### ISSUE TITLE
User Password loginnya apa bang?

### ISSUE THREAD

**Issue by dmzhari** [dewanakl/undangan#27]
![image](https://github.com/dewanakl/undangan/assets/45622512/cb392bed-6e19-403c-ad86-73e1f0b79fc4)

**Comment by dewanakl** [comment]
Sebelumnya sudah deploy sendiri ya mas
Kemudian untuk default email dan passwordnya itu
user@example.com dan 1-8

**Comment by dmzhari** [comment]
untuk data key nya darimana itu gan

**Comment by dewanakl** [comment]
Dari dashboardnya mas

**Comment by dmzhari** [comment]
kok saya error gini yah mas
![image](https://github.com/dewanakl/undangan/assets/45622512/c686c4fe-40bf-4246-949c-72cb2c5232de)

**Comment by dmzhari** [comment]
check comment pun tidak bisa mas error
![image](https://github.com/dewanakl/undangan/assets/45622512/8997e399-67cb-4f8a-973e-bc87f2afb258)

**Comment by dewanakl** [comment]
Untuk databasenya bisa di ubah memakai supabase mas
Untuk elephant sql sudah tidak relevant lagi

**Comment by dmzhari** [comment]
waduh pantes aja mas makasih mas

**Comment by dewanakl** [comment]
Sama sama mas

**Comment by dmzhari** [comment]
![image](https://github.com/dewanakl/undangan/assets/45622512/0382464b-c1b4-4e8e-a109-7f2c37b31807)
kok jadi gak ada user nya mas tapi kalo masuk ke dashboard normal mas

**Comment by dmzhari** [comment]
waduh sudah beres mas terimakasih

**Comment by gandencoli11** [comment]
bang ini kok user ama password nya nggk bisa yaa
