### ISSUE TITLE
ini error kenapa yah mas kemarin normal aja tiba" sekarang kok error gini yah mas

### ISSUE THREAD

**Issue by dmzhari** [dewanakl/undangan#28]
![image](https://github.com/dewanakl/undangan/assets/45622512/b6f80c77-998f-4c5b-acfb-8a4e3d03dd98)

**Comment by dewanakl** [comment]
Untuk di vercel ubah juga function region pada singapore ada dibagian settings

**Comment by dmzhari** [comment]
kalo di vercel dibagian mana mas menu itu

**Comment by dmzhari** [comment]
termasuk yang backend nya juga mas?

**Comment by dewanakl** [comment]
Ada di settings kemudian ada functions lalu ubah ke singapore dan redeoploy lagi

**Comment by dmzhari** [comment]
oke work lagi mas terimakasih banyak

**Comment by dewanakl** [comment]
Okey mas, sama sama
