### ISSUE TITLE
bantu deploy api ke vercel

### ISSUE THREAD

**Issue by wanshade** [dewanakl/undangan#3]
bang bisa bantu deploy ke vercel gak untuk api nya

**Comment by dewanakl** [comment]
bisa bang, untuk databasenya memakai cloud bang, kalau dulu saya pake elephantsql dia pake postgresql bang, gratis juga

**Comment by wanshade** [comment]
udah bikin instance di elephantsql cara deploy ke vercel nya gimana bang

**Comment by wanshade** [comment]
ganti env nya bang ? isian nya gimana

**Comment by dewanakl** [comment]
https://github.com/dewanakl/undangan-api

ada di readme ini bang, kalau kurang jelas, tanyakan lagi saja bang

**Comment by wanshade** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/41707274/235036343-0e323c5f-58c0-4918-b649-bfaf1405cee7.png)
muncul seperti ini bang

**Comment by dewanakl** [comment]
coba di lokal repository / di pc mas nya itu composer update dulu mas

lalu push lagi ke github otomatis si vercel akan deploy lagi kan mas

tungguin deploy selesai trus masuk ke vercelnya trus pilih project nya lalu klik tab deployments dan klik paling atas/terbaru kemudian ada titik 3 dan klik redeploy lagi mas

**Comment by dewanakl** [comment]
coba klik redeploy lalu liat log buildingnya mas

**Comment by wanshade** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/41707274/235086416-780aa45a-fac3-4857-9305-19ac51e18c8a.png)

**Comment by dewanakl** [comment]
composer json nya sepertinya nggak ada mas

**Comment by wanshade** [comment]
ada bang di repo nya, mungkin env nya salah? 
![Screenshot_5](https://user-images.githubusercontent.com/41707274/235087548-bf455d8b-9bc6-4c50-8c58-464217cd9fe9.png)

**Comment by dewanakl** [comment]
sudah betul mas

**Comment by wanshade** [comment]
cara betulin composer json nya gimna bang

**Comment by dewanakl** [comment]
coba ss lagi mas, di vscode ada file composer.json sama composer.lock nggak ?

**Comment by wanshade** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/41707274/235088992-60ce27f7-ef0e-47a9-92fc-19604bbc86c8.png)
ada bang

**Comment by dewanakl** [comment]
nggak ada folder api sama vercel.json nya mas

**Comment by wanshade** [comment]
wah udah bisa bang ,, makasih banyakk 
![Screenshot_7](https://user-images.githubusercontent.com/41707274/235092798-f84d59b9-9103-4717-aaa2-c45d659dbf86.png)

**Comment by dewanakl** [comment]
siap mas, tadi download ulang atau gimana mas?

**Comment by wanshade** [comment]
download ulang bang
