### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by Putrasalav** [dewanakl/undangan#36]
bang ini kenapa ya nama comment yg ditampilkan bukan nama yang komentar tapi nama akun yang di dashboard, tolong dibantu bang
![Cuplikan layar 2024-09-08 014157](https://github.com/user-attachments/assets/2434ff3e-2279-4260-9105-6dbc39129ccd)

**Comment by Putrasalav** [comment]
awalnya benar yang tampilkan nama yang sudah di isikan dikolom, tapi ketika di refresh berubah jadi nama user yg di dashboard

**Comment by dewanakl** [comment]
Jika membuka 2 sekaligus, sebaiknya undangan di incognito (samaran) dan dashboard di normal
kalau ingin jadi satu, harus refresh biar di hapus secara otomatis session-nya.

**Comment by Putrasalav** [comment]
Ok bang terimakasih, 
Izin pake scriptnya buat acara saya bang 🙏

**Comment by Putrasalav** [comment]
eh masih tetap sama bang, yang muncul nama user nya

**Comment by Putrasalav** [comment]
session-nya tidak kehapus otomatis

**Comment by dewanakl** [comment]
Boleh ss untuk errornya?

pastikan buka web admin di browser normal (tanpa incognito)
untuk undangan di incognito

jika tetap mau satu tab, pastikan selalu refresh (di tab yang di kunjungi (bisa web admin atau undangan))
agar berganti session.

dan pastikan menggunakan yang terbaru

**Comment by Putrasalav** [comment]
masih tetep bang yang muncul nama user, harusnya kan yang muncul nama yang mengisi comment
![Cuplikan layar 2024-09-10 011934](https://github.com/user-attachments/assets/36ba78a3-a352-49dd-b802-0f215cb95364)

**Comment by Putrasalav** [comment]
apa ada yg salah di file .env nya bang?
kalo jwt_key itu fungsinya buat apa ya bang
![Cuplikan layar 2024-09-10 012507](https://github.com/user-attachments/assets/dcd33af8-bf08-44ec-ba78-7507aca0014e)

**Comment by dewanakl** [comment]
Coba ss sewaktu inspect element pada localstorage nya
<img width="424" alt="image" src="https://github.com/user-attachments/assets/0ddd58c4-91a4-4319-8244-94a6cbf3d762">

**Comment by Putrasalav** [comment]
Begini bang responnya
![IMG_20240910_132901](https://github.com/user-attachments/assets/b3f2cd30-0694-4cce-b8e2-53ae05a4a4eb)

**Comment by dewanakl** [comment]
Coba gunakan yang terbaru ini mas
download lagi untuk undangannya pada github

**Comment by Putrasalav** [comment]
Ini saya pake undangan versi 3.0.8 bang

**Comment by Putrasalav** [comment]
Kalo boleh tau update lagi kapan bang, saya tunggu updatenya lagi aja deh

**Comment by dewanakl** [comment]
Bisa langsung download dari branch 3.x

**Comment by cr1m3** [comment]
Case yang sama.
Awalnya saya deploy backend di vercel dan supabase, ketika input comment, nama dan comment nya normal.
Ketika coba deploy backend di hosting dan mysql, nama dan commentnya menjadi User seperti gambar terlampir.
![image](https://github.com/user-attachments/assets/d7503a6b-3e72-4503-9df5-91cfaec25bef)

Masih belum ketemu, udah utak-atik mysql masih sama. Mohon dibantu mas. Terima kasih.

**Comment by dewanakl** [comment]
Pastikan gunakan extension OPcache dan mysqlnd / nd_pdo_mysql mas.

**Comment by cr1m3** [comment]
Makasih mas, sudah normal setelah aktifkan OPcache.

Open cPanel > PHP Selector > Extension > Checklist OPcache > Checklist mysqlnd / nd_pdo_mysql (salah satu).

**Case closed**
