### ISSUE TITLE
Pls make an english tutorial

### ISSUE THREAD

**Issue by gawldfeesh** [dewanakl/undangan#37]
I followed the video but i still can't figure out how to connect the backend to the frontend. Please make a step by step tutorial in english. I wanna use your template.

**Comment by dewanakl** [comment]
Thank you for reaching out! I apologize for the delay and for not being able to provide the tutorial in English due to time constraints. However, feel free to contact me via email or through the GitHub discussion tab, and I'll be happy to assist you further.

**Comment by gawldfeesh** [comment]
hello, how do i link the backend to the front end?

**Comment by dewanakl** [comment]
You can see the presentation slides (translate them yourself)
if you have any questions, please let me know

Thank you
