### ISSUE TITLE
Tambahan menu RSVP

### ISSUE THREAD

**Issue by cr1m3** [dewanakl/undangan#39]
Halo bg,
Bagaimana cara tambah menu di dashboard html untuk membuat undangan "kepada:" atau dear... seperti gambar terlampir?
Terima kasih.
![Capture](https://github.com/user-attachments/assets/2671c416-5065-4f58-9468-fb34ccfc9993)

**Comment by dewanakl** [comment]
Bisa langsung dibagian index html

seperti: https://ulems.my.id/?to=Teman+teman+semua
