### ISSUE TITLE
User Auto Replace

### ISSUE THREAD

**Issue by cr1m3** [dewanakl/undangan#41]
Hi bg,
Saat input comment, nama sesuai seperti yang diinput, saya coba backend pakai vercell dan database pakai supabase **Aman**
Tetapi saat pakai backend hosting dan database MySQL, comment yang diinput berubah menjadi User, seperti gambar berikut:
![image](https://github.com/user-attachments/assets/aea04d84-d945-4cf9-9336-18baf6921c8d)
![image](https://github.com/user-attachments/assets/4c31a2f4-e4bf-47de-8044-303f2aab2467)

Sudah normal setelah aktifkan OPcache.

Open cPanel > PHP Selector > Extension > Checklist OPcache > Checklist mysqlnd / nd_pdo_mysql (salah satu).
Thanks mas.

**Case closed**

**Comment by dewanakl** [comment]
Pastikan gunakan extension OPcache dan mysqlnd / nd_pdo_mysql mas

**Comment by dewanakl** [comment]
https://github.com/dewanakl/undangan/issues/36#issuecomment-2365228389
