### ISSUE TITLE
Hide & Show nomor rekening

### ISSUE THREAD

**Issue by cr1m3** [dewanakl/undangan#42]
Hi bang,
Bagaimana untuk buat hide & show rekening?
![IMG_5174](https://github.com/user-attachments/assets/6dcabeeb-cb2f-4079-a0a5-40be091b4efd)
Mohon dibantu, thanks bg

**Comment by cr1m3** [comment]
Reference :
https://youtu.be/MkvHPOT4RS8?si=qyOFUmh5F-qjlwoc

**Comment by dewanakl** [comment]
Untuk tujuannya apa ya mas kalau boleh tau?
Jika di copy pun akan tau juga nomer rekening nya

terima kasih

**Comment by cr1m3** [comment]
Mmm kurang sreg aja sih mas.. hehe

https://github.com/user-attachments/assets/66b387e4-f7e2-4522-9451-eeeb2aa42471

Kalau klik “klik disini” baru muncul, gitu mas..

**Comment by dewanakl** [comment]
<img width="430" alt="image" src="https://github.com/user-attachments/assets/f0872ffd-c2a8-4e6c-9b4f-e51616d8c2f6">
Mungkin bisa diubah seperti ini saja mas kalau dari saya

**Comment by dewanakl** [comment]
Saya close ya, jika ada yang ingin di tanyakan lagi silahkan open kembali issue ini
