### ISSUE TITLE
User dan password unauthorized

### ISSUE THREAD

**Issue by gandencoli11** [dewanakl/undangan#43]
bang ini user default ama password nya udh di ganti kah bang ?

![Screenshot 2024-11-27 033349](https://github.com/user-attachments/assets/0afdde07-3218-400e-bf49-b65e30cc426c)

**Comment by dewanakl** [comment]
Karena nantinya bisa diubah ubah untuk access key maka tidak untuk public mas
Bisa deploy sendiri untuk mengaksesnya, terima kasih
