### ISSUE TITLE
Pertanyaan

### ISSUE THREAD

**Issue by thatxxuc** [dewanakl/undangan#44]
Permisi mau tanya, cara menonaktifkan dark mode gimana mas? 

Terima kasih sebelumnya

**Comment by dewanakl** [comment]
https://github.com/dewanakl/undangan/blob/3f51d89c37fe7f9772762b56a063bd4b67dcb76a/index.html#L74

Bisa langsung ubah pada body html untuk hard ke light mode mas

**Comment by thatxxuc** [comment]
Oke mas, terima kasih banyak infonya
