### ISSUE TITLE
Error terjadi kesalaham ,otomatis reload halaman

### ISSUE THREAD

**Issue by nandiwardhanawidianto** [dewanakl/undangan#9]
![Screenshot from 2023-08-01 22-46-07](https://github.com/dewanakl/undangan/assets/62790811/ecb1c2f2-bdab-4450-85ef-ac18ad4809ea)

mulai dari install composer, migrasi, url pada body sudah betul semua. 
saya install undangan-api di localhost. dan alamat pada api juga sudah benar . tetapi masih saja error

mohon bantuannya

**Comment by dewanakl** [comment]
Hallo mas, coba masnya inspek element terlebih dahulu biar ketahuan
errornya mas

Pada tanggal Sel, 1 Agu 2023 22.49, nandiwardhanawidianto <
***@***.***> menulis:
